# Dataset parameters
dataset: miniimagenet
root_dir: './datasets'
cache_images: True

num_way: 10
num_shot: 5
target_num_way: 15

# Training parameters
optimizer: adam # Desired optimizer - must exist in build_graph()
learning_rate: 1e-2
total_steps: 3500
retraining_steps: 1000

# Model parameters
model_name: ConvModel
